name: Build Debian Package

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-deb-collector:
    uses: charlieh0tel/deb-workflows/.github/workflows/rust-build-deb.yml@main
    with:
      package: renogy-collector
      build-deps: "libdbus-1-dev"
      artifact-suffix: collector
    secrets: inherit

  build-deb-aprs:
    uses: charlieh0tel/deb-workflows/.github/workflows/rust-build-deb.yml@main
    with:
      package: renogy-aprs
      build-deps: "libdbus-1-dev"
      artifact-suffix: aprs
    secrets: inherit

  build-deb-archiver:
    uses: charlieh0tel/deb-workflows/.github/workflows/rust-build-deb.yml@main
    with:
      package: renogy-archiver
      artifact-suffix: archiver
    secrets: inherit

  build-deb-puller:
    uses: charlieh0tel/deb-workflows/.github/workflows/rust-build-deb.yml@main
    with:
      package: renogy-archiver-puller
      artifact-suffix: puller
    secrets: inherit
